<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/error_details.v1.proto

namespace Platform\Common\ErrorDetails\V1\Metadata;

class ErrorDetailsV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Duration::initOnce();
        $pool->internalAddGeneratedFile(
            '
œ	
common/error_details.v1.proto platform.common.error_details.v1";
	RetryInfo.
retry_delay (2.google.protobuf.Duration"2
	DebugInfo
stack_entries (	
detail (	"è
QuotaFailureL

violations (28.platform.common.error_details.v1.QuotaFailure.Violation1
	Violation
subject (	
description (	"©
	ErrorInfo
reason (	
domain (	K
metadata (29.platform.common.error_details.v1.ErrorInfo.MetadataEntry/
MetadataEntry
key (	
value (	:8"´
PreconditionFailureS

violations (2?.platform.common.error_details.v1.PreconditionFailure.Violation?
	Violation
type (	
subject (	
description (	"ô

BadRequestU
field_violations (2;.platform.common.error_details.v1.BadRequest.FieldViolation4
FieldViolation
field (	
description (	"7
RequestInfo

request_id (	
serving_data (	"`
ResourceInfo
resource_type (	
resource_name (	
owner (	
description (	"l
Help:
links (2+.platform.common.error_details.v1.Help.Link(
Link
description (	
url (	"3
LocalizedMessage
locale (	
message (	BM Platform\\Common\\ErrorDetails\\V1‚(Platform\\Common\\ErrorDetails\\V1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

