<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: echo/echo_service.v1.proto

namespace Platform\Echo\V1;

use Spiral\RoadRunner\GRPC;

interface EchoServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "platform.echo.v1.EchoService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GetStringRequest $in
    * @return GetStringResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GetString(GRPC\ContextInterface $ctx, GetStringRequest $in): GetStringResponse;
}
