<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/methods/get_string.v1.proto

namespace Platform\Echo\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.echo.v1.GetStringRequest</code>
 */
class GetStringRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \Platform\Echo\V1\Metadata\GetStringV1::initOnce();
        parent::__construct($data);
    }

}

