<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/error_details.v1.proto

namespace Platform\Common\ErrorDetails\V1;

if (false) {
    /**
     * This class is deprecated. Use Platform\Common\ErrorDetails\V1\BadRequest\FieldViolation instead.
     * @deprecated
     */
    class BadRequest_FieldViolation {}
}
class_exists(BadRequest\FieldViolation::class);
@trigger_error('Platform\Common\ErrorDetails\V1\BadRequest_FieldViolation is deprecated and will be removed in the next major release. Use Platform\Common\ErrorDetails\V1\BadRequest\FieldViolation instead', E_USER_DEPRECATED);

