<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/error_details.v1.proto

namespace Platform\Common\ErrorDetails\V1;

if (false) {
    /**
     * This class is deprecated. Use Platform\Common\ErrorDetails\V1\Help\Link instead.
     * @deprecated
     */
    class Help_Link {}
}
class_exists(Help\Link::class);
@trigger_error('Platform\Common\ErrorDetails\V1\Help_Link is deprecated and will be removed in the next major release. Use Platform\Common\ErrorDetails\V1\Help\Link instead', E_USER_DEPRECATED);

