<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/error_details.v1.proto

namespace Platform\Common\ErrorDetails\V1;

if (false) {
    /**
     * This class is deprecated. Use Platform\Common\ErrorDetails\V1\PreconditionFailure\Violation instead.
     * @deprecated
     */
    class PreconditionFailure_Violation {}
}
class_exists(PreconditionFailure\Violation::class);
@trigger_error('Platform\Common\ErrorDetails\V1\PreconditionFailure_Violation is deprecated and will be removed in the next major release. Use Platform\Common\ErrorDetails\V1\PreconditionFailure\Violation instead', E_USER_DEPRECATED);

