<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/echo_service.v1.proto

namespace Platform\Echo\V1\Metadata;

class EchoServiceV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Platform\Echo\V1\Metadata\GetStringV1::initOnce();
        \Platform\Common\ErrorDetails\V1\Metadata\ErrorDetailsV1::initOnce();
        \Platform\Common\ErrorStatus\V1\Metadata\ErrorStatusV1::initOnce();
        $pool->internalAddGeneratedFile(
            '
‰
echo/echo_service.v1.protoplatform.echo.v1common/error_details.v1.protocommon/error_status.v1.proto2c
EchoServiceT
	GetString".platform.echo.v1.GetStringRequest#.platform.echo.v1.GetStringResponseB/ÊPlatform\\Echo\\V1âPlatform\\Echo\\V1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

