<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo/methods/get_string.v1.proto

namespace Platform\Echo\V1\Metadata;

class GetStringV1
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¦
 echo/methods/get_string.v1.protoplatform.echo.v1"
GetStringRequest"#
GetStringResponse
result (	B/ÊPlatform\\Echo\\V1âPlatform\\Echo\\V1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

